### ISSUE TITLE
NO RNN_estimates

### ISSUE THREAD

**Issue by xinruxchen** [geekinglcq/opendac2018#1]
Hello there, 
It seems that you did a good job. I was trying the run the main.ipynb and got the error "ModuleNotFoundError: No module named 'RNN_estimate". I did not find any files related to RNN_estimated module in your project. Please let me know how to go on.

**Comment by geekinglcq** [comment]
Hi, we had fixed the problem which is related to some wrong version control operations.
You could clone the new code and try it.
Thank you.
