### ISSUE TITLE
您好，问您一个关于你这项工作意义的问题

### ISSUE THREAD

**Issue by mliwang** [geekinglcq/opendac2018#2]
我看数据集里面是给了作者单位的，那直接通过作者的单位去区分歧义作者作品不就完了吗为啥要做的这么复杂（我并没有恶意，希望您能给个解释）

**Comment by Legend94rz** [comment]
当然单位信息是一个十分重要的信息。
不过，有这么几种情况，不能仅用单位信息：
1. 同一个作者，在不同的文章里，所给出的单位往往是不一致的，比如在文章A里，他写的自己在Southeast University， 在文章B里可能写Southeast University(SEU)。只通过匹配该文本也是很困难的；
2. 即使是同一个单位，也有可能出现同名的情况；
3. 同一个作者，他需要视工作的不同，必须要写不同的单位，简单一个例子，他跳槽了。再一个例子，文章A和文章B需要挂靠在不同的单位下，A比如是他与企业的合作项目，他工作单位应该写企业；B比如是他高校的科研项目，他自然写高校。
所以， 确定是否是同一个人，既得看单位，更得利用其他信息。
具体的情况你可以把数据下载下来，实际尝试一下。

**Comment by geekinglcq** [comment]
我这里补充两点:
1. 对于中等规模的学校来说, 重名的现象都是非常普遍的. 再考虑到学者的跳槽, 歧义消解就更重要了.
2. 这类方法也可以用于其他的领域,如地名消歧等.
